"""
Milestone 6 follow-up: real city data extracted from the game's own archives via
sk-zk/Extractor (HashFS v2), not guessed from community sources -- see
docs/game-design.md for how this was pulled and verified. Each city id below is the
exact string used in economy.visited_cities/unlocked_dealers, confirmed against a real
save for 5 of these (kassel, hannover, frankfurt, nurnberg, bremen) before trusting the
rest. Display names are auto-derived (title-cased id) -- fine for most, some (accented
names, unusual capitalization) may read a little oddly and can be special-cased later.
"""

from __future__ import annotations

# dlc key -> option attribute name on Ets2AtsOptions (None = always included, base game)
DLC_OPTION_NAMES = {
    "going_east": "dlc_going_east",
    "scandinavia": "dlc_scandinavia",
    "vive_la_france": "dlc_vive_la_france",
    "italia": "dlc_italia",
    "beyond_baltic": "dlc_beyond_baltic",
    "road_to_black_sea": "dlc_road_to_black_sea",
    "west_balkans": "dlc_west_balkans",
    "iberia": "dlc_iberia",
    "greece": "dlc_greece",
}

# city_id -> (display_name, dlc_key or None for base game)
CITIES: dict[str, tuple[str, str | None]] = {
    'aberdeen': ('Aberdeen', None),
    'amsterdam': ('Amsterdam', None),
    'antwerp': ('Antwerp', None),
    'berlin': ('Berlin', None),
    'bern': ('Bern', None),
    'birmingham': ('Birmingham', None),
    'bratislava': ('Bratislava', None),
    'bremen': ('Bremen', None),
    'brno': ('Brno', None),
    'brussel': ('Brussel', None),
    'calais': ('Calais', None),
    'cambridge': ('Cambridge', None),
    'cardiff': ('Cardiff', None),
    'carlisle': ('Carlisle', None),
    'dijon': ('Dijon', None),
    'dortmund': ('Dortmund', None),
    'dover': ('Dover', None),
    'dresden': ('Dresden', None),
    'duisburg': ('Duisburg', None),
    'dusseldorf': ('Dusseldorf', None),
    'edinburgh': ('Edinburgh', None),
    'eindhoven': ('Eindhoven', None),
    'erfurt': ('Erfurt', None),
    'europoort': ('Europoort', None),
    'felixstowe': ('Felixstowe', None),
    'frankfurt': ('Frankfurt', None),
    'geneve': ('Geneve', None),
    'glasgow': ('Glasgow', None),
    'graz': ('Graz', None),
    'grimsby': ('Grimsby', None),
    'groningen': ('Groningen', None),
    'hamburg': ('Hamburg', None),
    'hannover': ('Hannover', None),
    'harwich': ('Harwich', None),
    'hull': ('Hull', None),
    'ijmuiden': ('Ijmuiden', None),
    'innsbruck': ('Innsbruck', None),
    'kassel': ('Kassel', None),
    'kiel': ('Kiel', None),
    'klagenfurt': ('Klagenfurt', None),
    'koln': ('Koln', None),
    'leipzig': ('Leipzig', None),
    'liege': ('Liege', None),
    'lille': ('Lille', None),
    'linz': ('Linz', None),
    'liverpool': ('Liverpool', None),
    'london': ('London', None),
    'luxembourg': ('Luxembourg', None),
    'lyon': ('Lyon', None),
    'magdeburg': ('Magdeburg', None),
    'manchester': ('Manchester', None),
    'mannheim': ('Mannheim', None),
    'metz': ('Metz', None),
    'milano': ('Milano', None),
    'munchen': ('Munchen', None),
    'newcastle': ('Newcastle', None),
    'nurnberg': ('Nurnberg', None),
    'osnabruck': ('Osnabruck', None),
    'paris': ('Paris', None),
    'plymouth': ('Plymouth', None),
    'poznan': ('Poznan', None),
    'prague': ('Prague', None),
    'reims': ('Reims', None),
    'rostock': ('Rostock', None),
    'rotterdam': ('Rotterdam', None),
    'salzburg': ('Salzburg', None),
    'sheffield': ('Sheffield', None),
    'southampton': ('Southampton', None),
    'strasbourg': ('Strasbourg', None),
    'stuttgart': ('Stuttgart', None),
    'swansea': ('Swansea', None),
    'szczecin': ('Szczecin', None),
    'torino': ('Torino', None),
    'travemunde': ('Travemunde', None),
    'trieste': ('Trieste', None),
    'venice': ('Venice', None),
    'verona': ('Verona', None),
    'wien': ('Wien', None),
    'wroclaw': ('Wroclaw', None),
    'zurich': ('Zurich', None),
    'bialystok': ('Bialystok', 'going_east'),
    'budapest': ('Budapest', 'going_east'),
    'bystrica': ('Bystrica', 'going_east'),
    'debrecen': ('Debrecen', 'going_east'),
    'gdansk': ('Gdansk', 'going_east'),
    'gdynia': ('Gdynia', 'going_east'),
    'katowice': ('Katowice', 'going_east'),
    'kosice': ('Kosice', 'going_east'),
    'krakow': ('Krakow', 'going_east'),
    'lodz': ('Lodz', 'going_east'),
    'lublin': ('Lublin', 'going_east'),
    'olsztyn': ('Olsztyn', 'going_east'),
    'ostrava': ('Ostrava', 'going_east'),
    'pecs': ('Pecs', 'going_east'),
    'szeged': ('Szeged', 'going_east'),
    'warszawa': ('Warszawa', 'going_east'),
    'aalborg': ('Aalborg', 'scandinavia'),
    'aarhus': ('Aarhus', 'scandinavia'),
    'bergen': ('Bergen', 'scandinavia'),
    'esbjerg': ('Esbjerg', 'scandinavia'),
    'frederikshv': ('Frederikshv', 'scandinavia'),
    'gedser': ('Gedser', 'scandinavia'),
    'goteborg': ('Goteborg', 'scandinavia'),
    'helsingborg': ('Helsingborg', 'scandinavia'),
    'hirtshals': ('Hirtshals', 'scandinavia'),
    'jonkoping': ('Jonkoping', 'scandinavia'),
    'kalmar': ('Kalmar', 'scandinavia'),
    'kapellskar': ('Kapellskar', 'scandinavia'),
    'karlskrona': ('Karlskrona', 'scandinavia'),
    'karlstad': ('Karlstad', 'scandinavia'),
    'kobenhavn': ('Kobenhavn', 'scandinavia'),
    'kristiansand': ('Kristiansand', 'scandinavia'),
    'linkoping': ('Linkoping', 'scandinavia'),
    'malmo': ('Malmo', 'scandinavia'),
    'nynashamn': ('Nynashamn', 'scandinavia'),
    'odense': ('Odense', 'scandinavia'),
    'orebro': ('Orebro', 'scandinavia'),
    'oslo': ('Oslo', 'scandinavia'),
    'sodertalje': ('Sodertalje', 'scandinavia'),
    'stavanger': ('Stavanger', 'scandinavia'),
    'stockholm': ('Stockholm', 'scandinavia'),
    'trelleborg': ('Trelleborg', 'scandinavia'),
    'uppsala': ('Uppsala', 'scandinavia'),
    'vasteraas': ('Vasteraas', 'scandinavia'),
    'vaxjo': ('Vaxjo', 'scandinavia'),
    'ajaccio': ('Ajaccio', 'vive_la_france'),
    'alban': ('Alban', 'vive_la_france'),
    'bastia': ('Bastia', 'vive_la_france'),
    'bayonne': ('Bayonne', 'vive_la_france'),
    'bonifacio': ('Bonifacio', 'vive_la_france'),
    'bordeaux': ('Bordeaux', 'vive_la_france'),
    'bourges': ('Bourges', 'vive_la_france'),
    'brest': ('Brest', 'vive_la_france'),
    'calvi': ('Calvi', 'vive_la_france'),
    'civaux': ('Civaux', 'vive_la_france'),
    'clermont': ('Clermont', 'vive_la_france'),
    'golfech': ('Golfech', 'vive_la_france'),
    'lacq': ('Lacq', 'vive_la_france'),
    'larochelle': ('Larochelle', 'vive_la_france'),
    'laurent': ('Laurent', 'vive_la_france'),
    'lehavre': ('Lehavre', 'vive_la_france'),
    'lemans': ('Lemans', 'vive_la_france'),
    'lile_rousse': ('Lile Rousse', 'vive_la_france'),
    'limoges': ('Limoges', 'vive_la_france'),
    'marseille': ('Marseille', 'vive_la_france'),
    'montpellier': ('Montpellier', 'vive_la_france'),
    'nantes': ('Nantes', 'vive_la_france'),
    'nice': ('Nice', 'vive_la_france'),
    'paluel': ('Paluel', 'vive_la_france'),
    'porto_vecchio': ('Porto Vecchio', 'vive_la_france'),
    'rennes': ('Rennes', 'vive_la_france'),
    'roscoff': ('Roscoff', 'vive_la_france'),
    'toulouse': ('Toulouse', 'vive_la_france'),
    'ancona': ('Ancona', 'italia'),
    'bari': ('Bari', 'italia'),
    'bologna': ('Bologna', 'italia'),
    'cagliari': ('Cagliari', 'italia'),
    'cassino': ('Cassino', 'italia'),
    'catania': ('Catania', 'italia'),
    'catanzaro': ('Catanzaro', 'italia'),
    'firenze': ('Firenze', 'italia'),
    'genova': ('Genova', 'italia'),
    'livorno': ('Livorno', 'italia'),
    'messina': ('Messina', 'italia'),
    'napoli': ('Napoli', 'italia'),
    'olbia': ('Olbia', 'italia'),
    'palermo': ('Palermo', 'italia'),
    'parma': ('Parma', 'italia'),
    'pescara': ('Pescara', 'italia'),
    'roma': ('Roma', 'italia'),
    'sangiovanni': ('Sangiovanni', 'italia'),
    'sassari': ('Sassari', 'italia'),
    'suzzara': ('Suzzara', 'italia'),
    'taranto': ('Taranto', 'italia'),
    'terni': ('Terni', 'italia'),
    'daugavpils': ('Daugavpils', 'beyond_baltic'),
    'helsinki': ('Helsinki', 'beyond_baltic'),
    'kaliningrad': ('Kaliningrad', 'beyond_baltic'),
    'kaunas': ('Kaunas', 'beyond_baltic'),
    'klaipeda': ('Klaipeda', 'beyond_baltic'),
    'kotka': ('Kotka', 'beyond_baltic'),
    'kouvola': ('Kouvola', 'beyond_baltic'),
    'kunda': ('Kunda', 'beyond_baltic'),
    'lahti': ('Lahti', 'beyond_baltic'),
    'liepaja': ('Liepaja', 'beyond_baltic'),
    'loviisa': ('Loviisa', 'beyond_baltic'),
    'luga': ('Luga', 'beyond_baltic'),
    'mazeikiai': ('Mazeikiai', 'beyond_baltic'),
    'naantali': ('Naantali', 'beyond_baltic'),
    'narva': ('Narva', 'beyond_baltic'),
    'olkiluoto': ('Olkiluoto', 'beyond_baltic'),
    'paldiski': ('Paldiski', 'beyond_baltic'),
    'panevezys': ('Panevezys', 'beyond_baltic'),
    'parnu': ('Parnu', 'beyond_baltic'),
    'petersburg': ('Petersburg', 'beyond_baltic'),
    'pori': ('Pori', 'beyond_baltic'),
    'pskov': ('Pskov', 'beyond_baltic'),
    'rezekne': ('Rezekne', 'beyond_baltic'),
    'riga': ('Riga', 'beyond_baltic'),
    'siauliai': ('Siauliai', 'beyond_baltic'),
    'sosnovy_bor': ('Sosnovy Bor', 'beyond_baltic'),
    'tallinn': ('Tallinn', 'beyond_baltic'),
    'tampere': ('Tampere', 'beyond_baltic'),
    'tartu': ('Tartu', 'beyond_baltic'),
    'turku': ('Turku', 'beyond_baltic'),
    'utena': ('Utena', 'beyond_baltic'),
    'valmiera': ('Valmiera', 'beyond_baltic'),
    'ventspils': ('Ventspils', 'beyond_baltic'),
    'vilnius': ('Vilnius', 'beyond_baltic'),
    'vyborg': ('Vyborg', 'beyond_baltic'),
    'artand': ('Artand', 'road_to_black_sea'),
    'bacau': ('Bacau', 'road_to_black_sea'),
    'brasov': ('Brasov', 'road_to_black_sea'),
    'bucuresti': ('Bucuresti', 'road_to_black_sea'),
    'burgas': ('Burgas', 'road_to_black_sea'),
    'calarasi': ('Calarasi', 'road_to_black_sea'),
    'cernavoda': ('Cernavoda', 'road_to_black_sea'),
    'cluj_napoca': ('Cluj Napoca', 'road_to_black_sea'),
    'constanta': ('Constanta', 'road_to_black_sea'),
    'craiova': ('Craiova', 'road_to_black_sea'),
    'edirne': ('Edirne', 'road_to_black_sea'),
    'galati': ('Galati', 'road_to_black_sea'),
    'giurgiu': ('Giurgiu', 'road_to_black_sea'),
    'hamzabeyli': ('Hamzabeyli', 'road_to_black_sea'),
    'hunedoara': ('Hunedoara', 'road_to_black_sea'),
    'iasi': ('Iasi', 'road_to_black_sea'),
    'istanbul': ('Istanbul', 'road_to_black_sea'),
    'kapikule': ('Kapikule', 'road_to_black_sea'),
    'karlovo': ('Karlovo', 'road_to_black_sea'),
    'kozloduy': ('Kozloduy', 'road_to_black_sea'),
    'mangalia': ('Mangalia', 'road_to_black_sea'),
    'nadlac': ('Nadlac', 'road_to_black_sea'),
    'pernik': ('Pernik', 'road_to_black_sea'),
    'pirdop': ('Pirdop', 'road_to_black_sea'),
    'pitesti': ('Pitesti', 'road_to_black_sea'),
    'pleven': ('Pleven', 'road_to_black_sea'),
    'plovdiv': ('Plovdiv', 'road_to_black_sea'),
    'resita': ('Resita', 'road_to_black_sea'),
    'ruse': ('Ruse', 'road_to_black_sea'),
    'sofia': ('Sofia', 'road_to_black_sea'),
    'targu_mures': ('Targu Mures', 'road_to_black_sea'),
    'tekirdag': ('Tekirdag', 'road_to_black_sea'),
    'timisoara': ('Timisoara', 'road_to_black_sea'),
    'varna': ('Varna', 'road_to_black_sea'),
    'veliko_tarnovo': ('Veliko Tarnovo', 'road_to_black_sea'),
    'banja_luka': ('Banja Luka', 'west_balkans'),
    'beograd': ('Beograd', 'west_balkans'),
    'bihac': ('Bihac', 'west_balkans'),
    'bijelo_polje': ('Bijelo Polje', 'west_balkans'),
    'bitola': ('Bitola', 'west_balkans'),
    'durres': ('Durres', 'west_balkans'),
    'fier': ('Fier', 'west_balkans'),
    'karakaj': ('Karakaj', 'west_balkans'),
    'koper': ('Koper', 'west_balkans'),
    'kragujevac': ('Kragujevac', 'west_balkans'),
    'ljubljana': ('Ljubljana', 'west_balkans'),
    'maribor': ('Maribor', 'west_balkans'),
    'mostar': ('Mostar', 'west_balkans'),
    'niksic': ('Niksic', 'west_balkans'),
    'nis': ('Nis', 'west_balkans'),
    'novi_sad': ('Novi Sad', 'west_balkans'),
    'novo_mesto': ('Novo Mesto', 'west_balkans'),
    'osijek': ('Osijek', 'west_balkans'),
    'podgorica': ('Podgorica', 'west_balkans'),
    'pristina': ('Pristina', 'west_balkans'),
    'rijeka': ('Rijeka', 'west_balkans'),
    'sarajevo': ('Sarajevo', 'west_balkans'),
    'skopje': ('Skopje', 'west_balkans'),
    'split': ('Split', 'west_balkans'),
    'tirana': ('Tirana', 'west_balkans'),
    'tuzla': ('Tuzla', 'west_balkans'),
    'vlore': ('Vlore', 'west_balkans'),
    'zadar': ('Zadar', 'west_balkans'),
    'zagreb': ('Zagreb', 'west_balkans'),
    'zenica': ('Zenica', 'west_balkans'),
    'a_coruna': ('A Coruna', 'iberia'),
    'albacete': ('Albacete', 'iberia'),
    'algeciras': ('Algeciras', 'iberia'),
    'almaraz': ('Almaraz', 'iberia'),
    'almeria': ('Almeria', 'iberia'),
    'badajoz': ('Badajoz', 'iberia'),
    'bailen': ('Bailen', 'iberia'),
    'barcelona': ('Barcelona', 'iberia'),
    'beja': ('Beja', 'iberia'),
    'bilbao': ('Bilbao', 'iberia'),
    'burgos': ('Burgos', 'iberia'),
    'ciudad_real': ('Ciudad Real', 'iberia'),
    'coimbra': ('Coimbra', 'iberia'),
    'cordoba': ('Cordoba', 'iberia'),
    'corticadas_de_lavre': ('Corticadas De Lavre', 'iberia'),
    'el_ejido': ('El Ejido', 'iberia'),
    'evora': ('Evora', 'iberia'),
    'faro': ('Faro', 'iberia'),
    'gijon': ('Gijon', 'iberia'),
    'granada': ('Granada', 'iberia'),
    'guarda': ('Guarda', 'iberia'),
    'huelva': ('Huelva', 'iberia'),
    'leon': ('Leon', 'iberia'),
    'lisboa': ('Lisboa', 'iberia'),
    'lleida': ('Lleida', 'iberia'),
    'madrid': ('Madrid', 'iberia'),
    'malaga': ('Malaga', 'iberia'),
    'mengibar': ('Mengibar', 'iberia'),
    'murcia': ('Murcia', 'iberia'),
    'navia': ('Navia', 'iberia'),
    'o_barco': ('O Barco', 'iberia'),
    'olhao': ('Olhao', 'iberia'),
    'pamplona': ('Pamplona', 'iberia'),
    'ponte_de_sor': ('Ponte De Sor', 'iberia'),
    'port_de_sagunt': ('Port De Sagunt', 'iberia'),
    'porto': ('Porto', 'iberia'),
    'puertollano': ('Puertollano', 'iberia'),
    'salamanca': ('Salamanca', 'iberia'),
    'santander': ('Santander', 'iberia'),
    'setubal': ('Setubal', 'iberia'),
    'sevilla': ('Sevilla', 'iberia'),
    'sines': ('Sines', 'iberia'),
    'soria': ('Soria', 'iberia'),
    'tarragona': ('Tarragona', 'iberia'),
    'teruel': ('Teruel', 'iberia'),
    'valencia': ('Valencia', 'iberia'),
    'valladolid': ('Valladolid', 'iberia'),
    'vandellos': ('Vandellos', 'iberia'),
    'vigo': ('Vigo', 'iberia'),
    'villarreal': ('Villarreal', 'iberia'),
    'zaragoza': ('Zaragoza', 'iberia'),
    'argostoli': ('Argostoli', 'greece'),
    'athens': ('Athens', 'greece'),
    'chania': ('Chania', 'greece'),
    'chios': ('Chios', 'greece'),
    'heraklion': ('Heraklion', 'greece'),
    'ioannina': ('Ioannina', 'greece'),
    'kalamata': ('Kalamata', 'greece'),
    'kavala': ('Kavala', 'greece'),
    'lamia': ('Lamia', 'greece'),
    'larissa': ('Larissa', 'greece'),
    'mitilini': ('Mitilini', 'greece'),
    'patras': ('Patras', 'greece'),
    'rhodes': ('Rhodes', 'greece'),
    'thessaloniki': ('Thessaloniki', 'greece'),
    'trikala': ('Trikala', 'greece'),
}

